# pytest.ini - atm dbt_utils causes this see https://github.com/dbt-labs/dbt-utils/issues/627
[pytest]
addopts = "--ignore=./dbt_kpis/dbt_packages"